### ISSUE TITLE
Could not find artifact com.alibaba.ververica:flink-cep:jar:1.15-vvr-6.0.2-api 

### ISSUE THREAD

**Issue by ChenShuai1981** [RealtimeCompute/ververica-cep-demo#3]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.584 s
[INFO] Finished at: 2022-11-26T16:48:07+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cep-demo: Could not resolve dependencies for project com.alibaba.ververica:cep-demo:jar:1.0-SNAPSHOT: Could not find artifact com.alibaba.ververica:flink-cep:jar:1.15-vvr-6.0.2-api in nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public) -> [Help 1]

**Comment by bgeng777** [comment]
Hi thanks for your feedback.
The jar is available in maven: https://mvnrepository.com/artifact/com.alibaba.ververica/flink-cep/1.15-vvr-6.0.2-api
Maybe you can check your m2 setting file or download the jar from the website and install it manually.
```
mvn install:install-file -Dfile=/path/to/flink-cep-1.15-vvr-6.0.2-api.jar -DgroupId=com.alibaba.ververica -DartifactId=flink-cep -Dversion=1.15-vvr-6.0.2-api -Dpackaging=jar

```
