### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.apache.flink.cep.dynamic.coordinator.DynamicCepOperatorCoordinatorProvider 	

### ISSUE THREAD

**Issue by qiaohanqing** [RealtimeCompute/ververica-cep-demo#6]
Caused by: java.lang.ClassNotFoundException: org.apache.flink.cep.dynamic.coordinator.DynamicCepOperatorCoordinatorProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)

**Comment by Melodyyy1016** [comment]
I also encountered this problem.
<img width="1149" alt="image" src="https://github.com/RealtimeCompute/ververica-cep-demo/assets/51019386/bd26e4b4-adff-4e3f-8dc7-66cccd3b5019">

**Comment by DavidSH92** [comment]
The README file of the project has already stated that this code must be running on Alibaba's Flink platform, and the dynamic CEP feature is only available in the commercial version. And there is no folder org/apache/flink/sep/dynamic/coordinator in this jar package 1.15-vvr-6.0.4 at all. So the source code of this project is only a usage example of the Alibaba Flink platform, not a true open-source project

**Comment by SunFA** [comment]
Since it's open source, why delete some of the code

**Comment by young138120** [comment]
where can find the jar contain the  org.apache.flink.cep.dynamic.coordinator.DynamicCepOperatorCoordinatorProvider

**Comment by young138120** [comment]
> Since it's open source, why delete some of the code

老哥，有什么比较好的方案吗？还是能搞的到这个缺失的包

**Comment by qiaohanqing** [comment]
> > Since it's open source, why delete some of the code
> 
> 老哥，有什么比较好的方案吗？还是能搞的到这个缺失的包

上阿里云给alibaba交钱，只能这么解决

**Comment by qiaohanqing** [comment]
> Since it's open source, why delete some of the code

I agree with you

**Comment by zfyjlf** [comment]
请问现在有人获取到完整的jar，里面能包含org/apache/flink/sep/dynamic/coordinator包吗？
